### ISSUE TITLE
Null pointer causing crash in debug builds.

### ISSUE THREAD

**Issue by Makogan** [gwihlidal/spirv-reflect-rs#24]
I suspect there is a bug in the library. In particular at line:

https://github.com/gwihlidal/spirv-reflect-rs/blob/b2c452750adfe9018057aabe2a8a92a87de02098/src/convert.rs#L66

It seems like it is possible for `ffi_type.members` to be null if  `ffi_type.member_count` is 0. However, rust considers this unsafe and will return the error:

```
unsafe precondition(s) violated: slice::from_raw_parts requires the pointer to be aligned and non-null, and the total size of the slice not to exceed `isize::MAX`
``` 

Thus no application using this crate can run correctly in debug mode.

OS: ubuntu 22.04
crate version: 0.2.3
rustc version: rustc 1.78.0-nightly (ef324565d 2024-02-27)

**Comment by Makogan** [comment]
I pushed a PR that addresses the issue. It's just a matter of explicitly checking for null pointers. In the process I also noticed that the rust crate points to a rather old commit of the C repo.

**Comment by Detrixukaon58** [comment]
Has there been any update on this bug? It is still appearing in the current crate, so I am assuming that it has not been addressed yet.

**Comment by speedy-lex** [comment]
Still happening to me and I'm not sure if @gwihlidal is active so it might be a while before he accepts the PR.

**Comment by speedy-lex** [comment]
As a temporary fix you can replace
`spirv-reflect = " . . . "`
with
`spirv-reflect = { git = "https://github.com/gfxstrand/spirv-reflect-rs.git" }`
in your Cargo.toml

**Comment by speedy-lex** [comment]
PR #27 has been closed and therefore this issue is resolved
